services:
  Siketyan\Loxcan\Scanner\Go\GoPackagePool:
    shared: true

  Siketyan\Loxcan\Scanner\Go\GoSumParser:
    arguments:
      $packagePool: '@Siketyan\Loxcan\Scanner\Go\GoPackagePool'
      $versionParser: '@Siketyan\Loxcan\Versioning\SemVer\SemVerVersionParser'

  Siketyan\Loxcan\Scanner\Go\GoScanner:
    arguments:
      $parser: '@Siketyan\Loxcan\Scanner\Go\GoSumParser'

  Siketyan\Loxcan\Scanner\Cargo\CargoPackagePool:
    shared: true

  Siketyan\Loxcan\Scanner\Cargo\CargoLockParser:
    arguments:
      $packagePool: '@Siketyan\Loxcan\Scanner\Cargo\CargoPackagePool'
      $versionParser: '@Siketyan\Loxcan\Versioning\SemVer\SemVerVersionParser'

  Siketyan\Loxcan\Scanner\Cargo\CargoScanner:
    arguments:
      $parser: '@Siketyan\Loxcan\Scanner\Cargo\CargoLockParser'

  Siketyan\Loxcan\Scanner\Composer\ComposerPackagePool:
    shared: true

  Siketyan\Loxcan\Scanner\Composer\ComposerLockParser:
    arguments:
      $packagePool: '@Siketyan\Loxcan\Scanner\Composer\ComposerPackagePool'
      $versionParser: '@Siketyan\Loxcan\Versioning\Composer\ComposerVersionParser'

  Siketyan\Loxcan\Scanner\Composer\ComposerScanner:
    arguments:
      $parser: '@Siketyan\Loxcan\Scanner\Composer\ComposerLockParser'

  Siketyan\Loxcan\Scanner\Npm\NpmPackagePool:
    shared: true

  Siketyan\Loxcan\Scanner\Npm\NpmLockParser:
    arguments:
      $packagePool: '@Siketyan\Loxcan\Scanner\Npm\NpmPackagePool'
      $versionParser: '@Siketyan\Loxcan\Versioning\SemVer\SemVerVersionParser'

  Siketyan\Loxcan\Scanner\Npm\NpmScanner:
    arguments:
      $parser: '@Siketyan\Loxcan\Scanner\Npm\NpmLockParser'

  Siketyan\Loxcan\Scanner\Pip\PipPackagePool:
    shared: true

  Siketyan\Loxcan\Scanner\Pip\PipLockParser:
    arguments:
      $packagePool: '@Siketyan\Loxcan\Scanner\Pip\PipPackagePool'
      $versionParser: '@Siketyan\Loxcan\Versioning\Simple\SimpleVersionParser'

  Siketyan\Loxcan\Scanner\Pip\PipScanner:
    arguments:
      $parser: '@Siketyan\Loxcan\Scanner\Pip\PipLockParser'

  Siketyan\Loxcan\Scanner\Pnpm\PnpmPackagePool:
    shared: true

  Siketyan\Loxcan\Scanner\Pnpm\PnpmLockParser:
    arguments:
      $packagePool: '@Siketyan\Loxcan\Scanner\Pnpm\PnpmPackagePool'
      $versionParser: '@Siketyan\Loxcan\Versioning\SemVer\SemVerVersionParser'

  Siketyan\Loxcan\Scanner\Pnpm\PnpmScanner:
    arguments:
      $parser: '@Siketyan\Loxcan\Scanner\Pnpm\PnpmLockParser'

  Siketyan\Loxcan\Scanner\Pub\PubPackagePool:
    shared: true

  Siketyan\Loxcan\Scanner\Pub\PubLockParser:
    arguments:
      $packagePool: '@Siketyan\Loxcan\Scanner\Pub\PubPackagePool'
      $versionParser: '@Siketyan\Loxcan\Versioning\SemVer\SemVerVersionParser'

  Siketyan\Loxcan\Scanner\Pub\PubScanner:
    arguments:
      $parser: '@Siketyan\Loxcan\Scanner\Pub\PubLockParser'

  Siketyan\Loxcan\Scanner\Uv\UvPackagePool:
    shared: true

  Siketyan\Loxcan\Scanner\Uv\UvLockParser:
    arguments:
      $packagePool: '@Siketyan\Loxcan\Scanner\Uv\UvPackagePool'
      $versionParser: '@Siketyan\Loxcan\Versioning\Simple\SimpleVersionParser'

  Siketyan\Loxcan\Scanner\Uv\UvScanner:
    arguments:
      $parser: '@Siketyan\Loxcan\Scanner\Uv\UvLockParser'

  Siketyan\Loxcan\Scanner\Yarn\YarnPackagePool:
    shared: true

  Siketyan\Loxcan\Scanner\Yarn\YarnLockParser:
    arguments:
      $packagePool: '@Siketyan\Loxcan\Scanner\Yarn\YarnPackagePool'
      $versionParser: '@Siketyan\Loxcan\Versioning\SemVer\SemVerVersionParser'

  Siketyan\Loxcan\Scanner\Yarn\YarnScanner:
    arguments:
      $parser: '@Siketyan\Loxcan\Scanner\Yarn\YarnLockParser'

  Siketyan\Loxcan\Scanner\ScannerResolver:
    arguments:
      $scanners:
        - '@Siketyan\Loxcan\Scanner\Cargo\CargoScanner'
        - '@Siketyan\Loxcan\Scanner\Composer\ComposerScanner'
        - '@Siketyan\Loxcan\Scanner\Go\GoScanner'
        - '@Siketyan\Loxcan\Scanner\Npm\NpmScanner'
        - '@Siketyan\Loxcan\Scanner\Pip\PipScanner'
        - '@Siketyan\Loxcan\Scanner\Pnpm\PnpmScanner'
        - '@Siketyan\Loxcan\Scanner\Pub\PubScanner'
        - '@Siketyan\Loxcan\Scanner\Uv\UvScanner'
        - '@Siketyan\Loxcan\Scanner\Yarn\YarnScanner'
