services:
  Composer\Semver\VersionParser: ~

  Siketyan\Loxcan\Versioning\Composer\ComposerVersionParser: ~

  Siketyan\Loxcan\Versioning\Composer\ComposerVersionComparator: ~

  Siketyan\Loxcan\Versioning\SemVer\SemVerVersionParser: ~

  Siketyan\Loxcan\Versioning\SemVer\SemVerVersionComparator: ~

  Siketyan\Loxcan\Versioning\Simple\SimpleVersionParser: ~

  Siketyan\Loxcan\Versioning\Simple\SimpleVersionComparator: ~

  Siketyan\Loxcan\Versioning\Unknown\UnknownVersionComparator: ~

  Siketyan\Loxcan\Versioning\VersionComparatorResolver:
    arguments:
      $comparators:
        - '@Siketyan\Loxcan\Versioning\SemVer\SemVerVersionComparator'
        - '@Siketyan\Loxcan\Versioning\Simple\SimpleVersionComparator'
        - '@Siketyan\Loxcan\Versioning\Composer\ComposerVersionComparator'
        - '@Siketyan\Loxcan\Versioning\Unknown\UnknownVersionComparator'
